import {
  Megaphone,
  CalendarClock,
  BookOpen,
  MapPin,
  Users,
  MessageCircleDashed,
  School,
  Notebook,
  Briefcase,
  Building2,
  Code2,
  Monitor,
  Home,
  Calendar,
  Globe,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  speakerphone: Megaphone,
  'calendar-event': CalendarClock,
  books: BookOpen,
  'map-search': MapPin,
  users: Users,
  'message-dots': MessageCircleDashed,
  school: School,
  notebook: Notebook,
  briefcase: Briefcase,
  building: Building2,
  code: Code2,
  'device-desktop': Monitor,
  home: Home,
  calendar: Calendar,
  world: Globe,
};
